// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcD7mmi5HQmvGLvrkvEGIHGyb27SUlC0o',
    appId: '1:766618032909:web:bc966f26c2c6d68395ee44',
    messagingSenderId: '766618032909',
    projectId: 'chat-app-bb7cc',
    authDomain: 'chat-app-bb7cc.firebaseapp.com',
    storageBucket: 'chat-app-bb7cc.firebasestorage.app',
    measurementId: 'G-7K8SK0L8B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1jL4nrezfIX-OA8a2Gh4kw6K127Hs2Xo',
    appId: '1:766618032909:android:5562f24674a8704695ee44',
    messagingSenderId: '766618032909',
    projectId: 'chat-app-bb7cc',
    storageBucket: 'chat-app-bb7cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUo6DT4HDEBZezV0Grdka5baXaDs8yBNw',
    appId: '1:766618032909:ios:c06e7df97c5d767895ee44',
    messagingSenderId: '766618032909',
    projectId: 'chat-app-bb7cc',
    storageBucket: 'chat-app-bb7cc.firebasestorage.app',
    iosBundleId: 'com.example.chatappProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUo6DT4HDEBZezV0Grdka5baXaDs8yBNw',
    appId: '1:766618032909:ios:c06e7df97c5d767895ee44',
    messagingSenderId: '766618032909',
    projectId: 'chat-app-bb7cc',
    storageBucket: 'chat-app-bb7cc.firebasestorage.app',
    iosBundleId: 'com.example.chatappProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcD7mmi5HQmvGLvrkvEGIHGyb27SUlC0o',
    appId: '1:766618032909:web:7447db1b71029f8595ee44',
    messagingSenderId: '766618032909',
    projectId: 'chat-app-bb7cc',
    authDomain: 'chat-app-bb7cc.firebaseapp.com',
    storageBucket: 'chat-app-bb7cc.firebasestorage.app',
    measurementId: 'G-4SQ1MH45SL',
  );
}
